import 'package:news_info/constant/asset_constant.dart';

class ListCategoryNameConstant {
  static Map<String, String> listCategoryName = {
    'terbaru': AssetConstant.categoryBreakingNews,
    'politik': AssetConstant.categoryPolitics,
    'hukum': AssetConstant.categoryLaw,
    'ekonomi': AssetConstant.categoryEconomy,
    'bola': AssetConstant.categoryFootball,
    'olahraga': AssetConstant.categorySport,
    'humaniora': AssetConstant.categoryHumanities,
    'lifestyle': AssetConstant.categoryLifeStyle,
    'hiburan': AssetConstant.categoryEntertainment,
    'dunia': AssetConstant.categoryWorld,
    'tekno': AssetConstant.categoryTechnology,
    'otomotif': AssetConstant.categoryAutomotive,
    'investment': AssetConstant.categoryInvestment,
    'news': AssetConstant.categoryNews,
    'market': AssetConstant.categoryMarket,
    'entrepreneur': AssetConstant.categoryEntrepreneur,
    'syariah': AssetConstant.categorySharia,
    'tech': AssetConstant.categoryTechnology,
    'opini': AssetConstant.categoryOpinion,
    'profil': AssetConstant.categoryProfile,
    'nasional': AssetConstant.categoryNational,
    'internasional': AssetConstant.categoryInternational,
    'gayaHidup': AssetConstant.categoryLifeStyle,
    'jakarta': AssetConstant.categoryJakarta,
    'gaya': AssetConstant.categoryLifeStyle,
    'khas': AssetConstant.categoryTypical,
    'sehat': AssetConstant.categoryHealth,
    'jateng': AssetConstant.categoryCentralJava,
    'celebrity': AssetConstant.categoryCelebrity,
    'sports': AssetConstant.categorySport,
    'economy': AssetConstant.categoryEconomy,
    'daerah': AssetConstant.categoryArea,
    'khazanah': AssetConstant.categoryTreasure,
    'islam': AssetConstant.categoryIslam,
    'leisure': AssetConstant.categoryLeisure,
    'metro': AssetConstant.categoryMetro,
    'ekbis': AssetConstant.categoryBusinesssEconomics,
    'international': AssetConstant.categoryInternational,
    'sains': AssetConstant.categoryScience,
    'edukasi': AssetConstant.categoryEducation,
    'kalam': AssetConstant.categoryKalam,
    'bisnis': AssetConstant.categoryBusiness,
    'entertainment': AssetConstant.categoryEntertainment,
    'health': AssetConstant.categoryHealth,
    'cantik': AssetConstant.categoryBeauty,
    'seleb': AssetConstant.categoryCelebrity,
    'travel': AssetConstant.categoryTravel,
    'difabel': AssetConstant.categoryDisabled,
    'creativelab': AssetConstant.categoryCreative,
    'inforial': AssetConstant.categoryInfo,
    'event': AssetConstant.categoryEvent,
    'superskor': AssetConstant.categorySuperSkor,
    'parapuan': AssetConstant.categoryLadies,
    'kesehatan': AssetConstant.categoryHealth,
  };

  static Map<String, String> englishCategoryName = {
    'terbaru': 'Latest',
    'politik': 'Politics',
    'hukum': 'Law',
    'ekonomi': 'Economy',
    'bola': 'Football',
    'olahraga': 'Sport',
    'humaniora': 'Humanities',
    'lifestyle': 'Lifestyle',
    'hiburan': 'Entertainment',
    'dunia': 'World',
    'tekno': 'Technology',
    'otomotif': 'Automotive',
    'investment': 'Investment',
    'news': 'News',
    'market': 'Market',
    'entrepreneur': 'Entrepreneur',
    'syariah': 'Sharia',
    'tech': 'Technology',
    'opini': 'Opinion',
    'profil': 'Profile',
    'nasional': 'National',
    'internasional': 'International',
    'gayaHidup': 'Lifestyle',
    'jakarta': 'Jakarta',
    'gaya': 'Lifestyle',
    'khas': 'Typical',
    'sehat': 'Health',
    'jateng': 'Central Java',
    'celebrity': 'Celebrity',
    'sports': 'Sport',
    'economy': 'Economy',
    'daerah': 'Area',
    'khazanah': 'Treasure',
    'islam': 'Islam',
    'leisure': 'Leisure',
    'metro': 'Metro',
    'ekbis': 'Business Eco',
    'international': 'International',
    'sains': 'Science',
    'edukasi': 'Education',
    'kalam': 'Kalam',
    'bisnis': 'Business',
    'entertainment': 'Entertainment',
    'health': 'Health',
    'cantik': 'Beauty',
    'seleb': 'Celebrity',
    'travel': 'Travel',
    'difabel': 'Disabled',
    'creativelab': 'Creative Lab',
    'inforial': 'Inforial',
    'event': 'Event',
    'superskor': 'Super Score',
    'parapuan': 'Ladies',
    'kesehatan': 'Health',
  };

  static String categoryNewsImage(String pathName) {
    return listCategoryName.containsKey(pathName)
        ? listCategoryName[pathName]!
        : AssetConstant.notFoundImage;
  }

  static String categoryNewsName(String pathName) {
    return englishCategoryName.containsKey(pathName)
        ? englishCategoryName[pathName]!
        : 'Unknown';
  }
}
